import React from "react";

export const metadata = {
  title: "Ecommerce-Register",
  description: "Generated by create next app",
};

export default function Register() {
  return <div>Register</div>;
}
